cloud:
    aws:
        credentials:
            accessKey: AKIARC2FVTKH2YZITIPM
            secretKey: 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
        s3:
            bucket: daotool
        region:
            static: ap-northeast-2
        stack:
            auto: false

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: admin
        url: jdbc:mysql://daotool-mypage.cnj8s2utcsrc.ap-northeast-2.rds.amazonaws.com:3306/DaoTool
        password: propwave0806!
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect


